[[pages]]
path = 'src/pages/card_distribution.py'
name = 'Card Distribution'
icon = ':bar_chart:'

[[pages]]
path = 'src/pages/chaos_soulbound.py'
name = 'Chaos Legion Soulbound'
icon = ':bar_chart:'

[[pages]]
path = 'src/pages/rebellion_soulbound.py'
name = 'Rebellion Soulbound'
icon = ':bar_chart:'
